///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SQLDMTestAutomation.SQLDMRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PreTopQueryPlan recording.
    /// </summary>
    [TestModule("6f686d30-e431-4f58-b29f-e44f275f288a", ModuleType.Recording, 1)]
    public partial class PreTopQueryPlan : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SQLDMTestAutomation.SQLDMTestAutomationRepository repository.
        /// </summary>
        public static SQLDMTestAutomation.SQLDMTestAutomationRepository repo = SQLDMTestAutomation.SQLDMTestAutomationRepository.Instance;

        static PreTopQueryPlan instance = new PreTopQueryPlan();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PreTopQueryPlan()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PreTopQueryPlan Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016Info, new RecordItemIndex(0));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Middle Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016Info, new RecordItemIndex(1));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016.Click(System.Windows.Forms.MouseButtons.Middle);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016Info, new RecordItemIndex(2));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(3));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.Queries' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.QueriesInfo, new RecordItemIndex(4));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.Queries.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.Queries' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.QueriesInfo, new RecordItemIndex(5));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.Queries.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureMode' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureModeInfo, new RecordItemIndex(6));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureMode.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureMode' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureModeInfo, new RecordItemIndex(7));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureMode.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitorInfo, new RecordItemIndex(9));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitorInfo, new RecordItemIndex(10));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBoxInfo, new RecordItemIndex(11));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox.MoveTo();
            Delay.Milliseconds(200);
            
            EnableQueryMonitor();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEvents' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEventsInfo, new RecordItemIndex(13));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEvents.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='true') on item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEvents'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEventsInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEventsInfo, "Checked", "true");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
