///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SQLDMTestAutomation.SQLDMRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PreTopFiveQueryPlans recording.
    /// </summary>
    [TestModule("0c58d386-0544-4c98-8177-1e0673e67c84", ModuleType.Recording, 1)]
    public partial class PreTopFiveQueryPlans : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SQLDMTestAutomation.SQLDMTestAutomationRepository repository.
        /// </summary>
        public static SQLDMTestAutomation.SQLDMTestAutomationRepository repo = SQLDMTestAutomation.SQLDMTestAutomationRepository.Instance;

        static PreTopFiveQueryPlans instance = new PreTopFiveQueryPlans();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PreTopFiveQueryPlans()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PreTopFiveQueryPlans Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016Info, new RecordItemIndex(0));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Middle Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016Info, new RecordItemIndex(1));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016.Click(System.Windows.Forms.MouseButtons.Middle);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016Info, new RecordItemIndex(2));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.T_MSSQL2016.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.Queries' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.QueriesInfo, new RecordItemIndex(4));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.Queries.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.Queries' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.QueriesInfo, new RecordItemIndex(5));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.Queries.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureMode' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureModeInfo, new RecordItemIndex(6));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureMode.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureMode' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureModeInfo, new RecordItemIndex(7));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SignatureMode.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitorInfo, new RecordItemIndex(9));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitorInfo, new RecordItemIndex(10));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBoxInfo, new RecordItemIndex(11));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox.MoveTo();
            Delay.Milliseconds(200);
            
            EnableQueryMonitor();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEvents' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEventsInfo, new RecordItemIndex(13));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEvents.MoveTo();
            Delay.Milliseconds(200);
            
            SelectEEandEQP();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='true') on item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEvents'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEventsInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectQueryDataUsingExtendedEventsInfo, "Checked", "true");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.DurationInfo, new RecordItemIndex(16));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.DurationInfo, new RecordItemIndex(17));
            Keyboard.PrepareFocus(repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.DurationInfo, new RecordItemIndex(18));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTopInfo, new RecordItemIndex(19));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTopInfo, new RecordItemIndex(20));
            Keyboard.PrepareFocus(repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5' with focus on 'SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTopInfo, new RecordItemIndex(21));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop.PressKeys("5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButtonInfo, new RecordItemIndex(22));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButtonInfo, new RecordItemIndex(23));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(24));
            Delay.Duration(1000, false);
            
            CommonMethods.ExcludeDMQ();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'AdvancedQueryFilterConfigurationDialog.OkButton' at Center.", repo.AdvancedQueryFilterConfigurationDialog.OkButtonInfo, new RecordItemIndex(26));
            repo.AdvancedQueryFilterConfigurationDialog.OkButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdvancedQueryFilterConfigurationDialog.OkButton' at Center.", repo.AdvancedQueryFilterConfigurationDialog.OkButtonInfo, new RecordItemIndex(27));
            repo.AdvancedQueryFilterConfigurationDialog.OkButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(28));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(29));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(30));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ExceptionMessageBoxForm.Yes' at Center.", repo.ExceptionMessageBoxForm.YesInfo, new RecordItemIndex(31));
            repo.ExceptionMessageBoxForm.Yes.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExceptionMessageBoxForm.Yes' at Center.", repo.ExceptionMessageBoxForm.YesInfo, new RecordItemIndex(32));
            repo.ExceptionMessageBoxForm.Yes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(33));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitorInfo, new RecordItemIndex(34));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitorInfo, new RecordItemIndex(35));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor.Click();
            Delay.Milliseconds(200);
            
            UnSelectEQM();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(37));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(38));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
