///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SQLDMTestAutomation.SQLDMRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TopQueryPlansCPUusageMS recording.
    /// </summary>
    [TestModule("31316d95-79ee-455d-94b8-917cb9e484e5", ModuleType.Recording, 1)]
    public partial class TopQueryPlansCPUusageMS : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SQLDMTestAutomation.SQLDMTestAutomationRepository repository.
        /// </summary>
        public static SQLDMTestAutomation.SQLDMTestAutomationRepository repo = SQLDMTestAutomation.SQLDMTestAutomationRepository.Instance;

        static TopQueryPlansCPUusageMS instance = new TopQueryPlansCPUusageMS();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TopQueryPlansCPUusageMS()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TopQueryPlansCPUusageMS Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.DurationInfo, new RecordItemIndex(0));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.DurationInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.DurationInfo, new RecordItemIndex(2));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTopInfo, new RecordItemIndex(3));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTopInfo, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5' with focus on 'SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop'.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTopInfo, new RecordItemIndex(5));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.SelectTop.PressKeys("5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Open' at 7;8.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.OpenInfo, new RecordItemIndex(6));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Open.MoveTo("7;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Open' at 7;8.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.OpenInfo, new RecordItemIndex(7));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Open.Click("7;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLdmDesktopClient1.CPUUsageMilliseconds' at 85;13.", repo.SQLdmDesktopClient1.CPUUsageMillisecondsInfo, new RecordItemIndex(8));
            repo.SQLdmDesktopClient1.CPUUsageMilliseconds.Click("85;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButtonInfo, new RecordItemIndex(9));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButtonInfo, new RecordItemIndex(10));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.AdvancedOptionsButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            CommonMethods.ExcludeDMQ();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'AdvancedQueryFilterConfigurationDialog.OkButton' at Center.", repo.AdvancedQueryFilterConfigurationDialog.OkButtonInfo, new RecordItemIndex(13));
            repo.AdvancedQueryFilterConfigurationDialog.OkButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdvancedQueryFilterConfigurationDialog.OkButton' at Center.", repo.AdvancedQueryFilterConfigurationDialog.OkButtonInfo, new RecordItemIndex(14));
            repo.AdvancedQueryFilterConfigurationDialog.OkButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(15));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(16));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(17));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ExceptionMessageBoxForm.Yes' at Center.", repo.ExceptionMessageBoxForm.YesInfo, new RecordItemIndex(18));
            repo.ExceptionMessageBoxForm.Yes.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExceptionMessageBoxForm.Yes' at Center.", repo.ExceptionMessageBoxForm.YesInfo, new RecordItemIndex(19));
            repo.ExceptionMessageBoxForm.Yes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(20));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitorInfo, new RecordItemIndex(21));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor' at Center.", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitorInfo, new RecordItemIndex(22));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.ConfigureQueryMonitor.Click();
            Delay.Milliseconds(200);
            
            UnSelectEQM();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(24));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(25));
            repo.SQLDM.MonitoredSqlServerInstancePropertiesDial.OkButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(26));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
